In [2]:
# Naive Bayes

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [15]:
# Feature Scaling   ### feature scaling do not improve
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [12]:
y_pred=classifier.predict(X_test)

In [13]:
from sklearn.metrics import confusion_matrix

In [14]:
confusion_matrix(y_test,y_pred)

array([[65,  3],
       [ 7, 25]], dtype=int64)

# project on iris data set

In [16]:
from sklearn.datasets import load_iris

In [17]:
iris=load_iris()

In [18]:
X=iris.data

In [19]:
y=iris.target

In [20]:
from sklearn.model_selection import train_test_split

In [22]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [26]:
from sklearn.naive_bayes import GaussianNB

In [27]:
claa=GaussianNB()

In [29]:
claa.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [30]:
confusion_matrix(y_test,claa.predict(X_test))

array([[11,  0,  0],
       [ 0, 13,  0],
       [ 0,  1,  5]], dtype=int64)

In [33]:
from sklearn.metrics import classification_report

In [34]:
classification_report(y_test,claa.predict(X_test))

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        11\n           1       0.93      1.00      0.96        13\n           2       1.00      0.83      0.91         6\n\n   micro avg       0.97      0.97      0.97        30\n   macro avg       0.98      0.94      0.96        30\nweighted avg       0.97      0.97      0.97        30\n'

In [35]:
claa.class_count_

array([39., 37., 44.])

In [37]:
confusion_matrix(y_train,claa.predict(X_train))

array([[39,  0,  0],
       [ 0, 34,  3],
       [ 0,  3, 41]], dtype=int64)

In [38]:
claa.class_prior_

array([0.325     , 0.30833333, 0.36666667])

In [43]:
claa.score(X_test,y_test)

0.9666666666666667

In [44]:
claa.score(X_train,y_train)

0.95

# project on lungcap data

In [59]:
data=pd.read_csv("C://Users//sandY//Desktop//New Microsoft Office Excel Worksheet (7).csv")

In [60]:
data.head()

LungCap  Age  Height Smoke  Gender Caesarean
0    6.475    6    62.1    no    male        no
1   10.125   18    74.7   yes  female        no
2    9.550   16    69.7    no  female       yes
3   11.125   14    71.0    no    male        no
4    4.800    5    56.9    no    male        no

In [61]:
X=data.iloc[:,0:5]

In [65]:
y=data.iloc[:,5].values

In [66]:
X=pd.get_dummies(X,drop_first=True)

In [68]:
X=X.iloc[:,:].values

In [80]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)
# Feature Scaling   ### feature scaling do not improve
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [81]:
clas=GaussianNB()

In [82]:
clas.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [83]:
y_pred=clas.predict(X_test)

In [84]:
confusion_matrix(y_test,y_pred)

array([[95, 19],
       [29,  2]], dtype=int64)

In [85]:
confusion_matrix(y_train,clas.predict(X_train))

array([[410,  37],
       [114,  19]], dtype=int64)

In [86]:
clas.score(X_test,y_test)

0.6689655172413793

In [87]:

from sklearn.model_selection import cross_val_score
d=cross_val_score(estimator=clas,X=X_train,y=y_train,cv=10)

In [88]:
d.mean()

0.7396674766987603

# project on text classification

In [97]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import operator

In [98]:
from sklearn.datasets import fetch_20newsgroups

In [167]:
categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']

In [217]:
news_train=fetch_20newsgroups(subset="train",categories=categories,shuffle=True)

In [218]:
news_test=fetch_20newsgroups(subset="test",categories=categories,shuffle=True)

In [171]:
print(news_train.keys())

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])


In [172]:
print(news_train["target_names"])

['alt.atheism', 'comp.graphics', 'sci.med', 'soc.religion.christian']


In [109]:
from sklearn.feature_extraction.text import CountVectorizer

In [137]:
name=["the quick brown fox jumped over the lazy dog","the dog ","the fox"]

In [138]:
vector=CountVectorizer()

In [139]:
vector.fit(name)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [140]:
print("vocublary : "+str(vector.vocabulary_)+'\n\n')

vocublary : {'the': 7, 'quick': 6, 'brown': 0, 'fox': 2, 'jumped': 3, 'over': 5, 'lazy': 4, 'dog': 1}




In [141]:
## asign a unique no to each word also known as tokenize
## learning the vocublary from the raw data done by fit method

In [142]:
vector.vocabulary_

{'the': 7,
 'quick': 6,
 'brown': 0,
 'fox': 2,
 'jumped': 3,
 'over': 5,
 'lazy': 4,
 'dog': 1}

In [143]:
vector.transform(name)

<3x8 sparse matrix of type '<class 'numpy.int64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [144]:
## counting the ocuurance of each and every word done by transform method

In [145]:
# it is stored in an array of 1,8 ie 1 sample and 8 features

In [146]:
vector.get_feature_names()

['brown', 'dog', 'fox', 'jumped', 'lazy', 'over', 'quick', 'the']

In [147]:
print("feature names :"+str(vector.get_feature_names())+'\n\n')

feature names :['brown', 'dog', 'fox', 'jumped', 'lazy', 'over', 'quick', 'the']




In [148]:
counts=vector.transform(name)

In [149]:
counts.shape

(3, 8)

In [150]:
print("counts :"+"\n"+str(counts.toarray()))

counts :
[[1 1 1 1 1 1 1 2]
 [0 1 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 1]]


In [151]:
## come to text classificartion

In [173]:
from sklearn.feature_extraction.text import CountVectorizer

In [219]:
vector1=CountVectorizer()

In [220]:
vector1.fit(news_train.data)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [221]:
X_train=vector1.transform(news_train.data)

In [222]:
X_train.shape

(2257, 35788)


# term frequency counts how mant times a word occurs in any document

# inverse documnet frequencies this downscale the words that appears alot in  document

In [282]:
## calculate the idf for each word and assigns lowest value of 1 to the most freqvent word in document

In [194]:
from sklearn.feature_extraction.text import TfidfTransformer

In [195]:
vectorizer=TfidfTransformer()

In [223]:
X_train=vectorizer.fit_transform(X_train)

In [224]:
X_train.shape

(2257, 35788)

In [199]:
########### test data

In [228]:
X_test=vector1.transform(news_test.data)

In [229]:
X_test=vectorizer.transform(X_test)

In [230]:
X_test.shape

(1502, 35788)

In [215]:
#### classifier

In [231]:
from sklearn.naive_bayes import MultinomialNB

In [232]:
classi=MultinomialNB().fit(X_train,news_train.target)

In [234]:
y_pred=classi.predict(X_test)

In [235]:
confusion_matrix(news_test.target,y_pred)

array([[192,   2,   6, 119],
       [  2, 347,   4,  36],
       [  2,  11, 322,  61],
       [  2,   2,   1, 393]], dtype=int64)

In [238]:
from sklearn.metrics import accuracy_score,classification_report

In [242]:
print(classification_report(news_test.target,y_pred,target_names=news_test.target_names))

                        precision    recall  f1-score   support

           alt.atheism       0.97      0.60      0.74       319
         comp.graphics       0.96      0.89      0.92       389
               sci.med       0.97      0.81      0.88       396
soc.religion.christian       0.65      0.99      0.78       398

             micro avg       0.83      0.83      0.83      1502
             macro avg       0.89      0.82      0.83      1502
          weighted avg       0.88      0.83      0.84      1502



In [243]:
## usindg pipeline it can be done

In [244]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

In [245]:

text_clf = Pipeline([('vect', TfidfVectorizer()), 
                      ('clf', MultinomialNB()) ])

# train the model
text_clf.fit(news_train.data, news_train.target)
# Predict the test cases
predicted = text_clf.predict(news_test.data)



In [246]:
from sklearn import metrics
from sklearn.metrics import accuracy_score
import numpy as np

print('Accuracy achieved is ' + str(np.mean(predicted == news_test.target)))
print(metrics.classification_report(news_test.target, predicted, target_names=news_test.target_names)),
metrics.confusion_matrix(news_test.target, predicted)

Accuracy achieved is 0.8348868175765646
                        precision    recall  f1-score   support

           alt.atheism       0.97      0.60      0.74       319
         comp.graphics       0.96      0.89      0.92       389
               sci.med       0.97      0.81      0.88       396
soc.religion.christian       0.65      0.99      0.78       398

             micro avg       0.83      0.83      0.83      1502
             macro avg       0.89      0.82      0.83      1502
          weighted avg       0.88      0.83      0.84      1502



array([[192,   2,   6, 119],
       [  2, 347,   4,  36],
       [  2,  11, 322,  61],
       [  2,   2,   1, 393]], dtype=int64)

In [251]:
print("accuracy is :" ,accuracy_score(news_test.target,y_pred))

accuracy is : 0.8348868175765646


# using random forest

In [266]:
from sklearn.ensemble import RandomForestClassifier

In [267]:
rf=RandomForestClassifier(criterion="entropy",n_estimators=100,random_state=0)

In [268]:
rf.fit(X_train,news_train.target)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [269]:
confusion_matrix(news_test.target,rf.predict(X_test))

array([[205,  20,  24,  70],
       [  3, 375,   7,   4],
       [ 13, 127, 247,   9],
       [  3,  21,   6, 368]], dtype=int64)

In [271]:
accuracy_score(news_test.target,rf.predict(X_test))

0.7956058588548602

# using svm

In [278]:
svc=SVC(kernel="linear",random_state=0)

In [279]:
svc.fit(X_train,news_train.target)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [280]:
confusion_matrix(news_test.target,svc.predict(X_test))

array([[264,   6,  13,  36],
       [  3, 375,   6,   5],
       [  4,  27, 361,   4],
       [  3,   9,   3, 383]], dtype=int64)

In [281]:
accuracy_score(news_test.target,svc.predict(X_test))

0.9207723035952063